### ISSUE TITLE
Fix issue where multiple category labels are applied to issue

### ISSUE THREAD

**Issue by monkut** [monkut/kippo#117]
Currently, if multiple `category:{label}` labels are applied to an issue it will not be properly processed when the event is digested by the webhook event processor, resulting in the following error:

```

[ERROR] ValueError: Multiple Category labels applied on issue: https://github.com/{org}/{repo}/issues/{issuenumber}
Traceback (most recent call last):  
File "/var/task/handler.py", line 609, in lambda_handler    return LambdaHandler.lambda_handler(event, context)  
File "/var/task/handler.py", line 243, in lambda_handler    return handler.handler(event, context)  
File "/var/task/handler.py", line 377, in handler    result = self.run_function(app_function, event, context)  
File "/var/task/handler.py", line 282, in run_function    result = app_function(event, context)  
File "/var/task/zappa/asynchronous.py", line 272, in route_lambda_task    return run_message(message)  
File "/var/task/zappa/asynchronous.py", line 308, in run_message    **message['kwargs']  
File "/var/task/octocat/functions.py", line 182, in process_webhookevent_ids    processed_counts = processor.process_webhook_events(webhookevents)  
File "/var/task/octocat/functions.py", line 522, in process_webhook_events    result_state = eventtype_processing_method(webhookevent)  
File "/var/task/octocat/functions.py", line 304, in _process_projectcard_event    category =　get_github_issue_category_label(issue)  
File "/var/task/octocat/functions.py", line 127, in get_github_issue_category_label    raise ValueError(f"Multiple Category labels applied on issue: {issue.html_url}") | [ERROR] ValueError: Multiple Category labels applied on issue: https://github.com/kiconiaworks/jt-tabacco-classification-02/issues/35 Traceback (most recent call last):   
File "/var/task/handler.py", line 609, in lambda_handler     return LambdaHandler.lambda_handler(event, context)   
File "/var/task/handler.py", line 243, in lambda_handler     return handler.handler(event, context)   File "/var/task/handler.py", line 377, in handler     result = self.run_function(app_function, event, context)   
File "/var/task/handler.py", line 282, in run_function     result = app_function(event, context)   
File "/var/task/zappa/asynchronous.py", line 272, in route_lambda_task     return run_message(message)   
File "/var/task/zappa/asynchronous.py", line 308, in run_message     **message['kwargs']   
File "/var/task/octocat/functions.py", line 182, in process_webhookevent_ids     processed_counts = processor.process_webhook_events(webhookevents)   File "/var/task/octocat/functions.py", line 522, in process_webhook_events     result_state = eventtype_processing_method(webhookevent)   
File "/var/task/octocat/functions.py", line 304, in _process_projectcard_event     category = get_github_issue_category_label(issue)   
File "/var/task/octocat/functions.py", line 127, in get_github_issue_category_label     
raise ValueError(f"Multiple Category labels applied on issue: {issue.html_url}")

```

**Comment by monkut** [comment]
Merged, closing.
