### ISSUE TITLE
Create Milestones in Separate projects results in 500 error

### ISSUE THREAD

**Issue by monkut** [monkut/kippo#120]
When a repository already has a same/similar Milestone attached to it a 422 is returned by GITHUB
```

2020-09-15T17:52:32.664+09:00Copy2020-09-15 08:52:32,662 [ERROR] (django.request) log_response: Internal Server Error: /prod/admin/projects/activekippoproject/XXX/change/ | 2020-09-15 08:52:32,662 [ERROR] (django.request) log_response: Internal Server Error: /prod/admin/projects/activekippoproject/XXX/change/
  | 2020-09-15T17:52:32.664+09:00 | Traceback (most recent call last):
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/core/handlers/exception.py", line 34, in inner
  | 2020-09-15T17:52:32.664+09:00 | response = get_response(request)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/core/handlers/base.py", line 115, in _get_response
  | 2020-09-15T17:52:32.664+09:00 | response = self.process_exception_by_middleware(e, request)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/core/handlers/base.py", line 113, in _get_response
  | 2020-09-15T17:52:32.664+09:00 | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/contrib/admin/options.py", line 606, in wrapper
  | 2020-09-15T17:52:32.664+09:00 | return self.admin_site.admin_view(view)(*args, **kwargs)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/utils/decorators.py", line 142, in _wrapped_view
  | 2020-09-15T17:52:32.664+09:00 | response = view_func(request, *args, **kwargs)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/views/decorators/cache.py", line 44, in _wrapped_view_func
  | 2020-09-15T17:52:32.664+09:00 | response = view_func(request, *args, **kwargs)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/contrib/admin/sites.py", line 223, in inner
  | 2020-09-15T17:52:32.664+09:00 | return view(request, *args, **kwargs)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/contrib/admin/options.py", line 1648, in change_view
  | 2020-09-15T17:52:32.664+09:00 | return self.changeform_view(request, object_id, form_url, extra_context)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/utils/decorators.py", line 45, in _wrapper
  | 2020-09-15T17:52:32.664+09:00 | return bound_method(*args, **kwargs)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/utils/decorators.py", line 142, in _wrapped_view
  | 2020-09-15T17:52:32.664+09:00 | response = view_func(request, *args, **kwargs)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/contrib/admin/options.py", line 1529, in changeform_view
  | 2020-09-15T17:52:32.664+09:00 | return self._changeform_view(request, object_id, form_url, extra_context)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/contrib/admin/options.py", line 1573, in _changeform_view
  | 2020-09-15T17:52:32.664+09:00 | self.save_related(request, form, formsets, not add)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/contrib/admin/options.py", line 1116, in save_related
  | 2020-09-15T17:52:32.664+09:00 | self.save_formset(request, form, formset, change=change)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/projects/admin.py", line 290, in save_formset
  | 2020-09-15T17:52:32.664+09:00 | obj.delete()
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/db/models/base.py", line 919, in delete
  | 2020-09-15T17:52:32.664+09:00 | return collector.delete()
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/db/models/deletion.py", line 289, in delete
  | 2020-09-15T17:52:32.664+09:00 | sender=model, instance=obj, using=self.using
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/dispatch/dispatcher.py", line 175, in send
  | 2020-09-15T17:52:32.664+09:00 | for receiver in self._live_receivers(sender)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/django/dispatch/dispatcher.py", line 175, in <listcomp>
  | 2020-09-15T17:52:32.664+09:00 | for receiver in self._live_receivers(sender)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/projects/models.py", line 578, in cleanup_github_milestones
  | 2020-09-15T17:52:32.664+09:00 | instance.update_github_milestones(close=True)
  | 2020-09-15T17:52:32.664+09:00 | File "/var/task/projects/models.py", line 520, in update_github_milestones
  | 2020-09-15T17:52:32.664+09:00 | f"422 response from github, milestone may already exist for repository: " f"{repository.name}"
  | 2020-09-15T17:52:32.664+09:00 | projects.models.GithubMilestoneAlreadyExists: 422 response from github, milestone may already exist for repository: {REPOSSITORY_NAME}

```

**Comment by monkut** [comment]
merged, closing
