### ISSUE TITLE
manage.py migrate fails

### ISSUE THREAD

**Issue by dhassault** [monkut/kippo#27]
Hi Monkut! 
Hope you're fine!!
I was trying to run Kippo locally and when I run python `manage.py migrate` in the directory `kippo`, I have this error:

```
/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Operations to perform:
  Apply all migrations: accounts, admin, auth, contenttypes, octocat, projects, reversion, sessions, social_django, tasks
Running migrations:
  Applying projects.0001_initial...Traceback (most recent call last):
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 294, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: near "[]": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 91, in database_forwards
    schema_editor.create_model(model)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 312, in create_model
    self.execute(sql, params or None)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 294, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: near "[]": syntax error
```
The container for the db is running well: 
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
39934c85c4fe        postgres            "docker-entrypoint.s…"   33 minutes ago      Up 33 minutes       0.0.0.0:5432->5432/tcp   postgres
```

And the db "kippo" was created inside the container. I'm working inside the virtualenv "kippo" created by `pipenv install --dev`

Did I forget something?

Thanks!

**Comment by dhassault** [comment]
I could do the migration by editing `base.py`
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mydatabase',
        'USER': 'mydatabaseuser',
        'PASSWORD': 'mypassword',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}```

But now `python manage.py migrate` is failing also
```
/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(octocat, githubrepository) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 113, in loaddata
    self.load_label(fixture_label)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 177, in load_label
    obj.save(using=self.using)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/core/serializers/base.py", line 219, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/models/base.py", line 812, in _save_table
    forced_update)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/models/base.py", line 861, in _do_update
    return filtered._update(values) > 0
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/models/query.py", line 712, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/me/.local/share/virtualenvs/kippo-EorfaTpu/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: Problem installing fixture '/home/me/Documents/Projects/kippo/kippo/accounts/fixtures/initial_data.json': Could not load contenttypes.ContentType(pk=15): duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(octocat, githubrepository) already exists.
```

I have to set my own token? Where should I do it?

**Comment by dhassault** [comment]
It seems there is a (at least one) duplicate in the database. It happens in Telos also. We have no clear/easy solution to solve this. How should I do?

**Comment by monkut** [comment]
I updated the readme slightly.

If your just getting started, I suggest going in and creating a new database.
It appears from your traceback that `migrate` is trying to create entries that already exist.

Try with a 'fresh' database and see if you get the same issue.

**Comment by monkut** [comment]
with pgcli:
```
$ pgcli -h 127.0.0.1 -U postgres
Server: PostgreSQL 10.4
Version: 1.10.3
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
postgres@127:postgres> CREATE DATABASE kippo_new;              
```
